### ISSUE TITLE
EF Core 6.0 Support

### ISSUE THREAD

**Issue by dean-shanghai** [jsakamoto/EntityFrameworkCore.IndexAttribute#13]
Exception while EF Core updated to 6.0 preview
"missing method: ITypeBase.get_ClrType"

**Comment by jsakamoto** [comment]
Thank you for reporting!
I'm going to fix this issue, but unfortunately, I'm too busy to start debugging until next week.
Please give me some time.

**Comment by jsakamoto** [comment]
@dean-shanghai 
Could you try the latest preview version of this package?

- https://www.nuget.org/packages/Toolbelt.EntityFrameworkCore.IndexAttribute/5.0.1-preview.1.0

**Comment by dean-shanghai** [comment]
Updated, this exception seems to be gone. my routing system is failing, will test more later.
