### ISSUE TITLE
Support for IndexAttribute.IsClustered

### ISSUE THREAD

**Issue by EdwinOtten** [jsakamoto/EntityFrameworkCore.IndexAttribute#3]
First off, thanks for sharing your code! 👍

I'm just quoting the readme here:
> This library is designed to have the same syntax as EF 6.x [Index] annotation.

Do you have any plans to support the `IsClustered` property? I'm using it in an EF6 project and it is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.schema.indexattribute.isclustered?view=entity-framework-6.2.0#System_ComponentModel_DataAnnotations_Schema_IndexAttribute_IsClustered) on MSDN as being part of EF 6.2.0. If you appreciate it I might be able to work on this and drop a PR. Let me know what you think!

**Comment by jsakamoto** [comment]
Could you try to use "Toolbelt.EntityFrameworkCore.IndexAttribute.**SqlServer**" v.1.0.0.1-beta instead of "Toolbelt.EntityFrameworkCore.IndexAttribute" ?

- https://www.nuget.org/packages/Toolbelt.EntityFrameworkCore.IndexAttribute.SqlServer/1.0.0.1-beta

## How to use?

Annotate your model like this:

```csharp
public class Person
{
  [PrimaryKey(IsClustered = false)] // <- DONT FORGET THIS LINE.
  public int Id { get; set; }

  [Index(IsClustered = true)]
  public int Age { get; set; }
}
```

And invoke "BuildIndexesFromAnnotations**ForSqlServer**()" extension method in `DbContext.OnModelCreating()`.

```csharp
public class MyDbContext : DbContext
{
  public DbSet<Person> People { get; set; }
  ...
  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    base.OnModelCreating(modelBuilder);
    modelBuilder.BuildIndexesFromAnnotationsForSqlServer();
  }
}
```

If you forget annotate a non-clustered primary key, you will get an exception like bellow:

```
System.Data.SqlClient.SqlException : 
  Cannot create more than one clustered index on table 'People'. 
  Drop the existing clustered index 'PK_People' before creating another.
```

**Comment by EdwinOtten** [comment]
> Could you try to use "Toolbelt.EntityFrameworkCore.IndexAttribute.**SqlServer**" v.1.0.0.1-beta instead of "Toolbelt.EntityFrameworkCore.IndexAttribute" ?

Works like a charm! 🎉

I just generated a migration using your beta version and the resulting migration contains the correct annotation: `.Annotation("SqlServer:Clustered", false)`. Just like the one I used earlier. 

**Disclaimer:** I only tried the `[Index(IsUnique = false, IsClustered = false)]` combination because that's the one my project requires. I didn't test `IsClustered = true`.

**Comment by jsakamoto** [comment]
I released official versions today.

- https://www.nuget.org/packages/Toolbelt.EntityFrameworkCore.IndexAttribute.SqlServer/1.0.0.2
- https://www.nuget.org/packages/Toolbelt.EntityFrameworkCore.IndexAttribute/2.1.0
- https://www.nuget.org/packages/Toolbelt.EntityFrameworkCore.IndexAttribute.Attribute/1.1.0.4
