### ISSUE TITLE
Microsoft.EntityFrameworkCore 3.0.0 support

### ISSUE THREAD

**Issue by BertusVanZyl** [jsakamoto/EntityFrameworkCore.IndexAttribute#4]
See this url:
https://github.com/aspnet/EntityFrameworkCore/issues/18183

There is a breaking change in 3.0.0. that is also breaking this package.

Specifically, the error is this:
`Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

The breaking change notice sais to do this:
"replace all ReferenceOwnershipBuilder with OwnedNavigationBuilder"

**Comment by jsakamoto** [comment]
Thank you for your request!

I published "EF Core IndexAttribute" v.3 for EF Core v.3 🎉 

- https://www.nuget.org/packages/Toolbelt.EntityFrameworkCore.IndexAttribute/3.0.0

Your report about breaking changes of EF Core v3 was very useful to release EFCore3 supported version.

Thanks!
