### ISSUE TITLE
No best type found for implicitly-typed array

### ISSUE THREAD

**Issue by hermesramos** [jsakamoto/EntityFrameworkCore.IndexAttribute#7]
Hi,

After including the SQL Server package, every time it is used the code **[Index(IsUnique = true)]**, it generates the error: _No best type found for implicitly-typed array_.

Bellow is a screenshot from Visual Studio, showing the error:

![image](https://user-images.githubusercontent.com/11175800/81131964-46a3f900-8f23-11ea-8dff-68f07495839f.png)

Attached is a simple new project, from scratch, to show the error.

Thank you in advance.

[WebApplication6.zip](https://github.com/jsakamoto/EntityFrameworkCore.IndexAttribute/files/4584577/WebApplication6.zip)

**Comment by pdhimate** [comment]
A simple work around is to use **new string []{}**

**Comment by jsakamoto** [comment]
Hi all, sorry too late!

I started investigating this issue right now, and I succeeded reproduce this problem.

I'm going to fix this issue.

**Comment by jsakamoto** [comment]
I fixed this issue and published v.3.2.1 of `Toolbelt.EntityFrameworkCore.IndexAttribute.SqlServer`.

- https://www.nuget.org/packages/Toolbelt.EntityFrameworkCore.IndexAttribute.SqlServer/3.2.1

Please try it out, and if it is still buggy, please send me a reply.

**Comment by hermesramos** [comment]
Thank you very much!
