### ISSUE TITLE
Bogus index created

### ISSUE THREAD

**Issue by hermesramos** [jsakamoto/EntityFrameworkCore.IndexAttribute#8]
Hi,

I have the following classes:

```
public class Test1
{
    public int Id { get; set; }
    [Index(IsUnique = true)]
    public string Column1 { get; set; }
    public string Column2 { get; set; }

    public ICollection<Test2> Test2 { get; set; }
}

public class Test2
 {
     public int Id { get; set; }
     public int Test1Id { get; set; }
     public string Column1 { get; set; }

     public Test1 Test1 { get; set; }
}
```
I do not know why, but ToolBelt is creating a bogus index, that is not defined:

```
migrationBuilder.CreateIndex(
 name: "IX_Test2_Test1Id1",
 table: "Test2",
 column: "Test1Id1");
```
Attached is a sample project to reproduce the issue.

Thanks in advance.

[WebApplication6.zip](https://github.com/jsakamoto/EntityFrameworkCore.IndexAttribute/files/4584575/WebApplication6.zip)

**Comment by jsakamoto** [comment]
@hermesramos Thank you for your report!

And, it is very helpful for me that you attached the whole of project files to this thread. This saved a lot of my time.

However, the migration code as below is generated by EFCore, not Toolbelt, I think.

```csharp
migrationBuilder.CreateIndex(
    name: "IX_Test2_Test1Id",
    table: "Test2",
    column: "Test1Id");
```

This index is required to make a relationship that is represented `Test2` navigation property of `Test1`.

Even If you comment out the calling of `BuildIndexesFromAnnotationsForSqlServer()` extension method and re-generate migration codes,

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    // Adds attributes' indexes to the database
    //modelBuilder.BuildIndexesFromAnnotationsForSqlServer();
}
```
 you will still see the migration code `CreateIndex(name: "IX_Test2_Test1Id", ...)` in the migration code.

**Comment by hermesramos** [comment]
You are right! Thank you very much!
